regular:
  Monday:
    - ['9:00', '20:00']
  Tuesday:
    - ['9:00', '19:00']
  Wednesday:
    - ['9:00', '18:30']
  Thursday:
    - ['9:00', '20:00']
  Friday:
    - ['9:00', '19:00']
  Saturday:
    - ['12:00', '18:00']
  Sunday: null
holidays:
  - date: 2025-12-13
    reason: RRR Week Saturday Hours
    hours:
      - ['9:00', '18:00']
  - date: [2025-12-15, 2025-12-18]
    reason: Finals Week Expansion
    hours:
      - ['09:00', '20:00']
  - date: 2025-12-19
    reason: Finals Week Friday Hours
    hours:
      - ['09:00', '17:00']
  - date: [2025-12-20, 2026-01-20]
    reason: Summer Break
  - date: 2026-01-31
    reason: ASUC Staff Training
    hours: Closed

