regular:
  Monday:
    - ['9:00', '20:00']
  Tuesday:
    - ['9:00', '19:00']
  Wednesday:
    - ['9:00', '18:00']
  Thursday:
    - ['9:00', '19:00']
  Friday:
    - ['9:00', '20:00']
  Saturday:
    - ['12:00', '18:00']
  Sunday: null
holidays:
  - date: [2018-11-21, 2018-11-25]
    reason: Thanksgiving Break
  - date: 2018-12-03
    reason: Late Lab Opening
    hours:
      - ['10:00', '18:00']
  - date: 2018-12-14
    reason: Last Day of Finals
    hours:
      - ['9:00', '14:00']
  - date: [2018-12-15, 2019-01-14]
    reason: Winter Break
  - date: 2019-02-16
    reason: Early Lab Closure
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-18
    reason: Presidents' Day
  - date: 2019-02-19
    reason: Early Lab Closure
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-20
    reason: Early Lab Closure # FAFSA Workshop
    hours:
      - ['9:00', '18:00']
  - date: 2019-02-28
    reason: Early Lab Closure # FAFSA Workshop
    hours:
      - ['9:00', '18:00']
  - date: 2019-03-19
    reason: Early Lab Closure # Cal VSA Resume Workshop
    hours:
      - ['9:00', '19:00']
  - date: [2019-03-23, 2019-03-31]
    reason: Spring Break
  - date: 2019-04-24
    reason: Early Lab Closure # IST Open House
    hours:
      - ['9:00', '15:00']
      - ['18:00', '20:00']
  - date: [2019-05-18, 2019-08-27]
    reason: Summer Break
  - date: 2019-09-02
    reason: Labor Day
  - date: 2019-09-03
    reason: Early Lab Closure # BoD moved from Labor Day to 9/3
    hours:
      - ['9:00', '19:00']
  - date: 2019-09-21
    reason: Internal Event # OCF Hack Day
  - date: 2019-09-25
    reason: Early Lab Closure # Yelp talk
    hours:
      - ['9:00', '18:00']
  - date: 2019-10-09
    reason: MLK Building Closure # Per campus announcement
  - date: 2019-10-10
    reason: Campus Power Outage # Per campus announcement
  - date: 2019-10-11
    reason: Campus Power Outage # Per campus announcement
  - date: 2019-10-16
    reason: Early Lab Closure # Facebook Talk
    hours:
      - ['9:00', '18:00']
  - date: 2019-10-23
    reason: Early Lab Closure # Nefeli Talk
    hours:
      - ['9:00', '18:00']
  - date: [2019-10-26, 2019-10-27]
    reason: Campus Power Outage # Per campus announcement
  - date: 2019-10-28
    reason: Campus Power Outage # Per campus announcement
  - date: 2019-11-11
    reason: Veterans Day
  - date: [2019-11-27, 2019-12-01]
    reason: Thanksgiving Break
  - date: 2019-12-04
    reason: Early Lab Closure # Security talk
    hours:
      - ['9:00', '18:00']
  - date: [2019-12-21, 2020-01-20]
    reason: Winter Break
  - date: 2020-02-08
    reason: Early Lab Closure # HackDay
    hours:
      - ['9:00', '14:00']
  - date: 2020-02-09
    reason: Afternoon Closure # no front desk staff
    hours:
      - ['9:00', '15:00']
      - ['18:00', '20:00']
  - date: 2020-02-17
    reason: Presidents' Day
  - date: [2020-03-10, 2020-03-20]
    reason: Public Health Closure
  - date: [2020-03-21, 2020-03-29]
    reason: Spring Break
  - date: [2020-03-30, 2020-05-15]
    reason: Public Health Closure
  - date: [2020-05-16, 2020-08-25]
    reason: Summer Break
  - date: 2021-08-25
    reason: Preparing for Reopening
  - date: 2021-08-26
    reason: Preparing for Reopening
  - date: 2021-08-27
    reason: Preparing for Reopening
  - date: 2021-08-28
    reason: Preparing for Reopening
  - date: 2021-08-29
    reason: Preparing for Reopening
  - date: 2021-09-05
    reason: MLK Closed
  - date: 2021-09-06
    reason: Labor Day
  - date: 2021-09-12
    reason: MLK Closed
  - date: 2021-09-19
    reason: MLK Closed
  - date: 2021-09-25
    reason: Internal staff social
    hours:
      - ['11:00', '16:00']
  - date: 2021-09-26
    reason: MLK Closed
  - date: 2021-10-02
    reason: Staff hack day
  - date: 2021-10-03
    reason: MLK Closed
  - date: 2021-10-07
    reason: Staff emergency
    hours:
      - ['10:30', '20:00']
  - date: 2021-10-10
    reason: MLK Closed
  - date: 2021-10-16
    reason: Internal Event  # OCF Resume Workshop
    hours:
      - ['11:00', '13:00']
  - date: 2021-10-17
    reason: MLK Closed
  - date: 2021-10-24
    reason: MLK Closed
  - date: 2021-10-30
    reason: Internal staff social
    hours:
      - ['11:00', '15:00']
  - date: 2021-10-31
    reason: MLK Closed
  - date: 2021-11-02
    reason: Staffing Issue
    hours:
      - ['13:00', '20:00']
  - date: 2021-11-06
    reason: Internal staff social
    hours:
      - ['11:00', '14:00']
  - date: 2021-11-07
    reason: MLK Closed
  - date: 2021-11-11
    reason: Veteran's Day
  - date: 2021-11-13
    reason: MLK Closed
  - date: 2021-11-14
    reason: MLK Closed
  - date: 2021-11-21
    reason: MLK Closed
  - date: 2021-11-22
    reason: Board of Directors Meeting
    hours:
      - ['9:00', '19:00']
  - date: 2021-11-23
    reason: Thanksgiving Break #no front desk staff
  - date: 2021-11-24
    reason: Thanksgiving Break
  - date: 2021-11-25
    reason: Thanksgiving Break
  - date: 2021-11-26
    reason: Thanksgiving Break
  - date: 2021-11-27
    reason: Thanksgiving Break
  - date: 2021-11-28
    reason: Thanksgiving Break
  - date: 2021-11-29
    reason: Morning Closure #no front desk staff
    hours:
      - ['13:00', '20:00']
  - date: 2021-12-05
    reason: MLK Closed
  - date: 2021-12-08
    reason: RRR Week Hours Expansion
    hours:
      - ['9:00', '19:00']
  - date: 2021-12-12
    reason: MLK Closed
  - date: 2021-12-15
    reason: Final Week Hours Expansion
    hours:
      - ['9:00', '20:00']
  - date: 2021-12-16
    reason: Finals Week #no front desk staff
  - date: 2021-12-17
    reason: Finals Week #no front desk staff
  - date: 2021-12-18
    reason: Finals Week #no front desk staff
  - date: [2021-12-19, 2022-01-17]
    reason: Winter Break
  - date: [2022-01-18, 2022-01-23]
    reason: Remote Instruction Closure
  - date: [2022-01-24, 2022-01-28]
    hours:
      - ['9:00', '18:00']
    reason: Reduced Building Hours
  - date: 2022-01-29
    reason: Closure
  - date: 2022-02-05
    reason: Internal staff social
    hours:
      - ['11:00', '16:00']
  - date: 2022-02-21
    reason: Presidents' Day
  - date: 2022-03-12
    reason: Internal Event # Hack Day
    hours:
      - ['11:00', '13:00']
  - date: [2022-03-20, 2022-03-26]
    reason: Spring Break
  - date: 2022-04-22
    reason: Unspecified # Hack Day
    hours:
      - ['9:00', '17:00']
  - date: 2022-05-04
    reason: Extended Lab Hours # for dead week
    hours:
      - ['9:00', '20:00']
  - date: 2022-05-07
    reason: Extended Lab Hours # for dead week
    hours:
      - ['9:00', '20:00']
  - date: [2022-05-14, 2022-08-28]
    reason: Summer Break
  - date: [2022-09-03, 2022-09-05]
    reason: Labor Day
  - date: 2022-11-05
    reason: Internal Event # Alumni Banquet
    hours:
      - ['10:00', '16:00']
  - date: [2022-11-11, 2022-11-12]
    reason: Veterans' Day
  - date: 2022-11-17
    reason: MLK Closed
  - date: [2022-11-24, 2022-11-27]
    reason: Thanksgiving Break
  - date: 2022-12-14
    reason: Finals Week hours
    hours:
      - ['9:00', '20:00']
  - date: 2022-12-16
    reason: Finals Week hours
    hours:
      - ['9:00', '17:00']
  - date: [2022-12-17, 2023-01-15]
    reason: Winter Break
  - date: [2023-01-16, 2023-01-22]
    reason: Preparing for Reopening
  - date: 2023-03-15
    reason: Internal Event # Palo Alto Networks Infosession
    hours:
      - ['9:00', '18:30']
  - date: [2023-03-25, 2023-04-02]
    reason: Spring Break
  - date: 2023-04-26
    reason: Building Event  # building fire drill
    hours:
      - ['9:30', '19:00']
  - date: 2023-05-01
    reason: RRR Week hours
    hours:
      - ['9:00', '22:00']
  - date: 2023-05-02
    reason: RRR Week hours
    hours:
      - ['8:00', '20:00']
  - date: 2023-05-03
    reason: RRR Week hours
    hours:
      - ['9:00', '22:00']
  - date: 2023-05-04
    reason: RRR Week hours
    hours:
      - ['9:00', '20:00']
  - date: 2023-05-05
    reason: RRR Week hours
    hours:
      - ['8:00', '21:00']
  - date: 2023-05-06
    reason: RRR Week hours
    hours:
      - ['10:00', '20:00']
  - date: [2023-05-13, 2023-08-27]
    reason: Summer Break
  - date: 2023-09-04
    reason: Labor Day
  - date: 2023-09-16
    reason: Reduced hours for staff event
    hours:
      - ['12:00', '16:00']
  - date: 2023-10-28
    reason: Reduced Hours for Internal Event # Halloween social
    hours:
      - ['12:00', '17:00']
  - date: 2023-11-10
    reason: Veteran's Day
  - date: [2023-11-20, 2023-11-25]
    reason: Thanksgiving Break
  - date: 2023-12-08
    reason: Extended hours
    hours:
    - ['9:00', '21:00']
  - date: 2023-12-09
    reason: Internal Event
    hours:
    - ['12:00', '17:00']
  - date: [2024-01-12, 2024-01-15]
    reason: Winter Break
  - date: [2024-01-16, 2024-01-21]
    reason: Preparing for Reopening
  - date: 2024-02-19
    reason: Presidents' Day
  - date: 2024-03-18
    reason: MLK Building Early Closure
    hours:
      - ['9:00', '17:00']
  - date: 2024-03-22
    reason: MLK Building Early Closure
    hours:
      - ['9:00', '17:00']
  - date: 2024-03-23
    reason: MLK Building Early Closure
    hours:
      - ['12:00', '17:00']
  - date: [2024-03-25, 2024-03-28]
    reason: Spring Break
  - date: 2024-03-29
    reason: MLK Closed in Observance of Holiday
  - date: [2024-05-22, 2024-09-02]
    reason: Summer Break
  - date: 2024-11-09
    reason: HKN EECS Day
    hours:
      - ['16:00', '18:00']
  - date: 2024-11-11
    reason: Veteran's Day
  - date: [2024-11-27, 2024-11-30]
    reason: Thanksgiving Break
  - date: 2024-12-10
    reason: RRR Week Hours
    hours:
      - ['9:00', '20:00']
  - date: 2024-12-12
    reason: RRR Week Hours
    hours:
      - ['9:00', '20:00']
  - date: 2024-12-13
    reason: RRR Week Hours
    hours:
      - ['9:00', '17:00']
  - date: 2024-12-14
    reason: RRR Week Hours
    hours:
      - ['10:00', '18:00']
  - date: [2024-12-16, 2024-12-20]
    reason: Finals Week Hours
    hours:
      - ['9:00', '20:00']
  - date: [2024-12-21, 2025-01-26]
    reason: Winter Break
  - date: 2025-02-17
    reason: Presidents Day
  - date: [2025-03-21, 2025-03-22]
    reason: Spring Break
    hours:
      - ['9:00', '17:00']
  - date: [2025-03-24, 2025-03-27]
    reason: Spring Break
    hours:
      - ['9:00', '17:00']
  - date: [2025-03-28, 2025-03-30]
    reason: Spring Break
  - date: 2025-05-02
    reason: Nix Meetup
    hours:
      - ['9:00', '18:00']
  - date: [2025-05-06, 2025-05-09]
    reason: RRR Week expansion
    hours:
      - ['9:00', '20:00']
  - date: 2025-05-10
    reason: RRR Week Saturday Hours
    hours:
      - ['10:00', '17:00']
  - date: [2025-05-12, 2025-05-16]
    reason: Finals Week expansion
    hours:
      - ['09:00', '20:00']
  - date: [2025-05-17, 2025-08-26]
    reason: Summer Break
  - date: [2025-08-27, 2025-08-30]
    reason: First Week of Instruction
  - date: 2025-09-01
    reason: Labor Day
