# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header">Planned Campus Power Outage</h4>
    <p>
      The OCF will be closed to take preventative measures against COVID-19.
      <br /><br />
      At this point, most other OCF services are expected to remain available throughout the closure, including webhosting and mail. We will be providing info as the situation changes.
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #e6b129;
    }
    #banner:hover {
      background-color: #e6b129;
    }
  </style>
