# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header"><b>Spring 2022</b> Lab Update</h4>
    <p>
      We're open starting this Monday, January 24, 2022. Our hours are temporarily reduced due to reduced building hours until further notice.<br /><br />
      See you in the lab!
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #a8e3ff;
    }
    #banner:hover {
      background-color: #a8e3ff;
    }
  </style>
