# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header">MLK Building Shutdown, Wednesday 10/09</h4>
    <p>
        On Wednesday 10/09, MLK Student Union building will be closed in anticipation of PG&E Public Safety Power Shutdown. Therefore, OCF <b>will be closed</b> that day.
        <br /><br />
        This OCF webpage may experience an outage. Status updates will be posted to our blog (<a href="https://status.ocf.berkeley.edu">status.ocf.berkeley.edu</a>) as necessary.
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #e6b129;
    }
    #banner:hover {
      background-color: #e6b129;
    }
  </style>
