# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: false

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header"><b>Subdomains for Student Organizations</b></h4>
    <p>
      The university is planning to revoke berkeley.edu subdomains for student organizations.<br />
      See <a href="https://www.ocf.berkeley.edu/announcements/2023-03-01/subdomains">ocf.io/subdomains</a> for more information and ways you can help oppose this change!
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #a8e3ff;
    }
    #banner:hover {
      background-color: #a8e3ff;
    }
  </style>
