# Authoritative meeting hours file.
#
# The meeting hours for all OCF-related groups are dynamically generated
# from the contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#

meeting-hours:
  Monday:
    - time: ['14:00', '15:00']
      subject: "Internal Meeting"
      short: "internal"
      irl: true
      virtual: false
  Tuesday:
  Wednesday:
    - time: ['19:00', '20:00']
      subject: "Board of Directors Meeting"
      short: "bod"
      irl: true
      virtual: true
    - time: ['20:00', '21:00']
      subject: "Staff Meeting"
      short: "staff"
      irl: true
      virtual: true
  Thursday:
  Friday:
    - time: ['17:00', '16:00']
      subject: "Web Team Meeting"
      short: "web"
      irl: true
      virtual: false
  Saturday:
    - time: ['14:00', '15:00']
      subject: "Kubernetes Interest Group Meeting"
      short: "kubernetes"
      irl: true
      virtual: false
    - time: ['15:00', '16:00']
      subject: "Linux/Infra Meeting"
      short: "linux/infra"
      irl: true
      virtual: false
  Sunday:
