# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
   - time: ['11:00', '12:30']
     staff: ['cooperc']
   - time: ['14:30', '17:00']
     staff: ['kmo']
  Tuesday:
   - time: ['14:00', '15:50']
     staff: ['fydai']
  Wednesday:
   - time: ['11:00', '12:30']
     staff: ['cooperc']
   - time: ['10:00', '12:00']
     staff: ['jaw']
  Thursday:
   - time: ['14:00', '15:50']
     staff: ['fydai']
   - time: ['14:30', '16:30']
     staff: ['jaw']
  Friday:
   - time: ['12:30', '14:00']
     staff: ['cooperc', 'ahujaabhik']
   - time: ['14:00', '16:00']
     staff: ['kmo']
   - time: ['16:00', '17:00']
     staff: ['bernardzhao', 'wqnguyen']
  Saturday:
  Sunday:

staff-positions:
 - username: "dphan"
   position: "General Manager"
 - username: "bernardzhao"
   position: "General Manager"
 - username: "cooperc"
   position: "Site Manager"
 - username: "jaw"
   position: "Site Manager"

# vim: set expandtab:ts=4:sw=4
