# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
  - time: ['11:00', '12:00']
    staff: ["jaysa", "rjz"]
  Tuesday:
  - time: ['8:30', '11:00']
    staff: ["ethanhu"]
  - time: ['14:20', '16:00']
    staff: ["oliverni"]
    cancelled: true
  - time: ['17:00', '19:00']
    staff: ["adi"]
  Wednesday:
  - time: ['11:00', '12:00']
    staff: ["jaysa"]
  Thursday:
  - time: ['14:10', '15:00']
    staff: ["btorres"]
  Friday:
  - time: ['10:15', '11:15']
    staff: ["ncograin"]
    cancelled: true
  - time: ['11:00', '12:00']
    staff: ["jaysa"]
  - time: ['9:00', '11:30']
    staff: ["ethanhu"]
  Saturday:
  Sunday:

staff-positions:
 - username: "ncograin"
   position: "General Manager Emeritus"
 - username: "kian"
   position: "General Manager Emeritus"
 - username: "jaysa"
   position: "General Manager"
 - username: "dapark"
   position: "General Manager"
 - username: "oliverni"
   position: "Site Manager"
 - username: "rjz"
   position: "It's Morbin' Time"
 - username: "etw"
   position: "Site Manager Emeritus"
 - username: "njha"
   position: "Site Manager Emeritus"
 - username: "anddone"
   position: "External Head"
 - username: "ethanhu"
   position: "External Head"
 - username: "adi"
   position: "Finance and DeCal Head"
 - username: "btorres"
   position: "External Head"

# vim: set expandtab:ts=4:sw=4
