# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
    - time: ['12:30', '13:30']
      staff: ["anddone"]
    - time: ['15:00', '16:00']
      staff: ["bencuan", "oliverni", "ianswong", "btorres"]
  Tuesday:
    - time: ['12:00', '13:00']
      staff: ["owent"]
      cancelled: false
  Wednesday:
  Thursday:
    - time: ['17:00', '18:00']
      staff: ["jyxzhang"]
  Friday:
    - time: ['12:00', '13:00']
      staff: ["lperez", "kian", "idham"]
      cancelled: false
    - time: ['15:00', '16:00']
      staff: ["adarshiyer"]
  Saturday:
    - time: ['12:00', '13:00']
      staff: ["yehchanyoo"]
  Sunday:

staff-positions:
 - username: "jyxzhang"
   position: "General Manager"
 - username: "njha"
   position: "General Manager"
 - username: "etw"
   position: "Site Manager"
 - username: "rjz"
   position: "Site Manager"
 - username: "anddone"
   position: "External Head"

# vim: set expandtab:ts=4:sw=4
