# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
   - time: ['9:00', '11:00']
     staff: ['minos']
   - time: ['10:00', '12:00']
     staff: ['cooperc']
     cancelled: true
   - time: ['12:30', '14:30']
     staff: ['wporr']
   - time: ['13:00', '14:00']
     staff: ['shmaeng']
     cancelled: true
   - time: ['16:00', '18:00']
     staff: ['gundralaa', 'snarain']
  Tuesday:
   - time: ['9:00', '10:30']
     staff: ['minos']
   - time: ['12:30', '15:30']
     staff: ['fydai']
   - time: ['14:00', '16:00']
     staff: ['php']
  Wednesday:
   - time: ['11:00', '12:30']
     staff: ['cooperc']
     cancelled: true
   - time: ['14:00', '16:00']
     staff: ['php']
   - time: ['15:00', '18:00']
     staff: ['snarain']
   - time: ['16:00', '17:00']
     staff: ['gleeb']
  Thursday:
   - time: ['9:00', '10:30']
     staff: ['minos']
   - time: ['12:00', '13:00']
     staff: ['bzh']
     cancelled: true
   - time: ['13:00', '14:00']
     staff: ['kmo']
   - time: ['18:30', '20:00']
     staff: ['andylo']
     cancelled: true
  Friday:
   - time: ['13:00', '14:00']
     staff: ['bencuan']
   - time: ['14:00', '15:00']
     staff: ['jaw']
   - time: ['14:00', '16:00']
     staff: ['php']
  Saturday:
   - time: ['14:00', '16:00']
     staff: ['php']
  Sunday:

staff-positions:
 - username: "php"
   position: "General Manager"
 - username: "cooperc"
   position: "General Manager"
 - username: "fydai"
   position: "Site Manager"
 - username: "ethanhs"
   position: "Site Manager"

# vim: set expandtab:ts=4:sw=4
