# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
  Tuesday:
  Wednesday:
  Thursday:
   - time: ['17:00', '18:00']
     staff: ["snarain"]
     cancelled: true
   - time: ['18:00', '20:00']
     staff: ["mdcha"]
     cancelled: false
  Friday:
   - time: ['15:30', '18:00']
     staff: ["mdcha"]
     cancelled: true
   - time: ['16:00', '17:00']
     staff: ["ethanhs", "jyxzhang", "bryli", "vijprathigudupu"]
     cancelled: false
  Saturday:
  Sunday:

staff-positions:
 - username: "ncberberi"
   position: "General Manager"
 - username: "snarain"
   position: "General Manager"
 - username: "ethanhs"
   position: "Site Manager"
 - username: "njha"
   position: "Site Manager"

# vim: set expandtab:ts=4:sw=4
