# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
  Tuesday:
    - time: ['14:10', '15:00']
      staff: ["ncograin"]
      cancelled: false
    - time: ['14:10', '15:30']
      staff: ['adarshiyer']
  Wednesday:
    - time: ['17:10', '18:00']
      staff: ['etw', 'njha']
  Thursday:
    - time: ['14:10', '15:30']
      staff: ['adarshiyer']
  Friday:
    - time: ['12:10', '13:00']
      staff: ["kian", "amangalampalli"]
      cancelled: false
    - time: ['15:10', '16:00']
      staff: ["btorres"]
      cancelled: false
  Saturday:
  Sunday:

staff-positions:
 - username: "ncograin"
   position: "General Manager"
 - username: "kian"
   position: "General Manager"
 - username: "etw"
   position: "Site Manager"
 - username: "njha"
   position: "Site Manager"
 - username: "anddone"
   position: "External Head"
 - username: "ethanhu"
   position: "Internal and External Head"
 - username: "amangalampalli"
   position: "Finance Head"
 - username: "btorres"
   position: "External Head"

# vim: set expandtab:ts=4:sw=4
