# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---


staff-hours:
  Monday:
     #- time: ['11:00', '12:00']
     #  staff: ["sbwilliams"]
  Tuesday:
     - time: ['12:00', '14:00']
       staff: ["sbwilliams"]
  Wednesday:
     - time: ['11:00', '12:00']
       staff: ["sbwilliams"]
  Thursday:
     - time: ['12:00', '14:00']
       staff: ["sbwilliams"]
  Friday:
     - time: ['13:30', '15:30']
       staff: ["sbwilliams"]
  Saturday:
  Sunday:

staff-positions:
 - username: "storce"
   position: "General Manager"
 - username: "ronitnath"
   position: "General Manager"
 - username: "oliverni"
   position: "Site Manager"
 - username: "laksith"
   position: "Site Manager"
 - username: "rjz"
   position: "It's Morbin' Time"
 - username: "lujkep"
   position: "Internal Head"
 - username: "jaysa"
   position: "Finance Head"
 - username: "sbwilliams"
   position: "Site Manager"
# vim: set expandtab:ts=4:sw=4
