# Authoritative staff hours file.
#
# The online staff hours page is dynamically generated based on the
# contents of this file.
#
# Be sure to use spaces instead of tabs for indentation of this file.
#
# An example staff hours entry looks like:
#
# staff-hours:
#  Monday:
#   - time: ['11:00', '13:00']
#     staff: ["gstaff"]
#  Tuesday:
#   - time: ['10:00', '11:00']
#     staff: ["bzh"]
#     cancelled: true
#  ...
#
# The `cancelled` field is optional, and defaults to false if not included.
#
# If you're modifying this file, if it passes the tests then you can just
# merge the change on github without needing an approval.
---

staff-hours:
  Monday:
    - time: ['16:00', '17:00']
      staff: ["bencuan"]
      cancelled: true
    - time: ['17:00', '18:00']
      staff: ["njha", "etw", "rjz"]
      cancelled: true
  Tuesday:
    - time: ['17:00', '18:00']
      staff: ["laksith"]
      cancelled: true
  Wednesday:
    - time: ['12:00', '13:00']
      staff: ["adarshiyer"]
      cancelled: true
  Thursday:
    - time: ['14:00', '15:00']
      staff: ["lperez", "kian"]
      cancelled: true
  Friday:
    - time: ['15:00', '16:00']
      staff: ["jyxzhang", "asomani"]
      cancelled: true
  Saturday:
  Sunday:

staff-positions:
 - username: "bencuan"
   position: "General Manager"
 - username: "jyxzhang"
   position: "General Manager"
 - username: "etw"
   position: "Site Manager"
 - username: "rjz"
   position: "Site Manager"
 - username: "njha"
   position: "Deputy Site Manager"

# vim: set expandtab:ts=4:sw=4
